### ISSUE TITLE
Commit number/ branch name for replaying BEHAVIOR 

### ISSUE THREAD

**Issue by jing-bi** [StanfordVL/bddl#10]
Dear author seems when the BEHAVIOR dataset is released, it was using another commit version of bddl.

Can you point out which commit number/ branch name for creating the BEHAVIOR dataset?

**Comment by mjlbach** [comment]
https://github.com/StanfordVL/bddl/commit/0a0b88ff27c24b1a7b08513f992e20f80b350fcd is probably good, we'll create a branch

**Comment by jing-bi** [comment]
Trying right now

**Comment by jing-bi** [comment]
i've tried a7c7583, 998e1cd98662d1d16436d32081e347d1b51f79e5, cd916820adc97422ff90cc77a1d98e5071fac5ed, ee7487801503bacf13d1564cd29a217598569e48, dfc3440a3b6e71fba63e2aad9c8e1adf3ec5cf5b, 8dc64f95f6cb812de1f57e4ddf303761dde99684 together with igibson  `behavior-replay` brench but still no luck, the lastest version with master igibson will yield result looks like this: https://github.com/StanfordVL/iGibson/issues/161#issuecomment-1022341060 not sure what caused the problem:

**Comment by mjlbach** [comment]
To clarify, you are on windows correct? Replay does not work on linux because the demos were recorded on windows (pybullet issue)

**Comment by jing-bi** [comment]
I thought only collect needs to be on windows, does replay have to be on windows as well?

**Comment by jing-bi** [comment]
Say if I have a perfect model that does exactly action with the VR recorded videos, but still, if I run my agent in the same scene, it will still fail I guess?

**Comment by roberto-martinmartin** [comment]
For full determinism, unfortunately, yes.
There are some low level operations that will return slightly different values depending on the OS. If you execute actions sequentially but their effect is slightly different (e.g., an object pushed moves a little bit different), the differences will accumulate and end up leading to completely different results.
This is not an iGibson/BEHAVIOR issue, it is an issue of determinism in PyBullet (and in most simulators).
The solution is to generate the pairs (state, action) on a windows machine and work with those. We provide the raw data for you to use on windows and generate whatever data you want, but we also provide a dataset with common observations that we generated on Windows.
what is what you are trying to do?

**Comment by roberto-martinmartin** [comment]
from your example: yes, a perfect model that does the exact same action may end up having a (tiny but accumulatable) different effect, leading possibly to failure

**Comment by roberto-martinmartin** [comment]
bottom line: if you want deterministic outcome for the actions (they have EXACTLY the same effect they had in VR when they were collected), you need the same system used when they were collected, i.e., Windows. 
but it is unclear why you need to execute the original actions "live". You can use the provided dataset of (observations, actions) created from a deterministic replay on Windows

**Comment by jing-bi** [comment]
I was trying to generate a high-resolution version of the dataset no matter if it's deterministic or not, long as the behavior in the video is aligned with the goal, I'm good.
When I'm trying to do it, I start to realize that even I have a perfect model, the evaluation will still be a problem.

But currently, I'm still trying to generate a replay video like here https://github.com/StanfordVL/iGibson/issues/161#issuecomment-1022341060

**Comment by roberto-martinmartin** [comment]
We will add additional notes on the documentation to make very clear all of this. 
Unfortunately, it is outside of what we can control. But, again, this is a common issue in most (all?) simulators: if you save a sequence of actions in one machine/OS (e.g. Mac) and replay on a completely different machine/OS (e.g. a Windows machine), there is no guarantee of obtaining the same results.
I hope this helps. Feel free to close all related issues and link to this issue that contains the explanation

**Comment by roberto-martinmartin** [comment]
I'm not sure I understand the "if it is deterministic or not". If you want the exact same outcome to the actions of the agent, you want a deterministic replay. if you do not care about the outcome of the actions to be exactly the same, then you do not need deterministic replay, but then there is not guarantee on what will happen, the demos could even fail

**Comment by jing-bi** [comment]
I see what you mean, the accumulated error is nothing we can control.
But I'm trying to say that the difference between the development environment when BEHAVIOR is created from the one I'm using caused the problem because from the generated video, it's like some internal config file changed.
I'm just trying to replicate everything BEHAVIOR has done to get started.

Btw, when creating the dataset, is there any chance we can download the action primitives segmentation of the raw data.

**Comment by mjlbach** [comment]
Yes, unfortunately the design of iGibson has had some fundamental changes/restructuring that would break determinism regardless of if you replayed on windows, there is no way to backport these changes.

**Comment by roberto-martinmartin** [comment]
I think what @jing-bi is referring to is that we need to make clear in the instructions what branches to use for all packages in order to get the demos working (even non-deterministically | with different outcome). We missed to define the version of bddl to use, we should add that info

**Comment by jing-bi** [comment]
Thanks for the reply, I was also trying to get the action primitive segmentation but found to get it I have to also replay the demo. Is there any chance we can download it somewhere without reply the raw data?

**Comment by roberto-martinmartin** [comment]
The demos are obtained from VR. There is no action primitives being used. What is the action primitive segmentation in that case?

**Comment by jing-bi** [comment]
I'm referring to this behavior/examples/behavior_demo_segmentation.py

I think this is used to generate segments from demo raw data, right?

**Comment by jing-bi** [comment]
If the action segmentation is not available, I can find a windows machine to do the replay.

Is there any way I can find out the proper version for all packages myself? 

Sorry to be such a bother, it's just the BEHAVIOR dataset is perfect for my project and I need to get everything asap.

**Comment by cgokmen** [comment]
No bother at all. Tomorrow I'll get you the exact versions of all of the repos you'll need to pull for the deterministic replay.

In the meantime, I can also send you some segmentations although they are incomplete and were made for a very particular purpose we were interested in (which means the demos were segmented with some very particular filters - only Open/Close/OnTop/Inside segments were produced). Give me your email address and I can send it. But I really think producing your own segmentations will be more meaningful. We'll help you get set up.
