### ISSUE TITLE
Remove/change objects in the original scene

### ISSUE THREAD

**Issue by juliasko** [StanfordVL/bddl#55]
Hi, 
Is it possible to change original scene (e.g. remove several objects from existing scene)?
If so, how, e.g. which file/s to edit?
Thank you

**Comment by sanjanasrivastava** [comment]
Hi Julia, BDDL lets you pick which objects are relevant to your task, but as with your previous question, the scene itself is simulator-dependent, not BDDL-dependent. You can once again handle this in the simulator code itself! One way would be to edit predefined scene files, as with your previous question.
