### ISSUE TITLE
intsallation failed

### ISSUE THREAD

**Issue by xdhhh** [StanfordVL/bddl#73]
after installing bddl, when i try to run the demos in README, i get an error 
ModuleNotFoundError: No module named 'bddl.activity_base'
Any solution?

**Comment by sanjanasrivastava** [comment]
Hi! Sorry about the confusion - the README was out of date. I can't update `master/README.md` right now as we are avoiding changes on that branch while OmniGibson is still under development, but I've updated the one on `develop`: https://github.com/StanfordVL/bddl/tree/develop. This one should help you use the current BDDL API! Do let us know if you have further questions.
